controller.player3.onEvent(ControllerEvent.Disconnected, function () {
    music.play(music.stringPlayable("C5 B A G F E D C ", 650), music.PlaybackMode.UntilDone)
})
controller.player3.onButtonEvent(ControllerButton.Right, ControllerButtonEvent.Repeated, function () {
    bubble.tilt_angle(bubble.Choice.Right)
})
controller.player1.onEvent(ControllerEvent.Disconnected, function () {
    music.play(music.stringPlayable("C5 B A G F E D C ", 650), music.PlaybackMode.UntilDone)
})
controller.player2.onButtonEvent(ControllerButton.A, ControllerButtonEvent.Pressed, function () {
    bubble.tossBubble()
    bubble.load_bubble()
    game.splash("Le toca a Lourdes")
})
controller.player3.onEvent(ControllerEvent.Connected, function () {
    music.play(music.stringPlayable("C D E F G A B C5 ", 650), music.PlaybackMode.UntilDone)
})
scene.onHitWall(SpriteKind.Bubble, function (sprite, location) {
    bubble.stick_to_wall(sprite, location)
})
controller.player3.onButtonEvent(ControllerButton.Left, ControllerButtonEvent.Repeated, function () {
    bubble.tilt_angle(bubble.Choice.Left)
})
controller.player2.onButtonEvent(ControllerButton.Left, ControllerButtonEvent.Repeated, function () {
    bubble.tilt_angle(bubble.Choice.Left)
})
controller.player2.onEvent(ControllerEvent.Disconnected, function () {
    music.play(music.stringPlayable("C5 B A G F E D C ", 650), music.PlaybackMode.UntilDone)
})
controller.player1.onButtonEvent(ControllerButton.A, ControllerButtonEvent.Pressed, function () {
    bubble.tossBubble()
    bubble.load_bubble()
    game.splash("Le toca a Juan")
})
controller.player3.onButtonEvent(ControllerButton.A, ControllerButtonEvent.Pressed, function () {
    bubble.tossBubble()
    bubble.load_bubble()
    game.splash("Le toca a Leoncio")
})
controller.player1.onButtonEvent(ControllerButton.Right, ControllerButtonEvent.Repeated, function () {
    bubble.tilt_angle(bubble.Choice.Right)
})
controller.player2.onEvent(ControllerEvent.Connected, function () {
    music.play(music.stringPlayable("C D E F G A B C5 ", 650), music.PlaybackMode.UntilDone)
})
controller.player2.onButtonEvent(ControllerButton.Right, ControllerButtonEvent.Repeated, function () {
    bubble.tilt_angle(bubble.Choice.Right)
})
controller.player1.onEvent(ControllerEvent.Connected, function () {
    music.play(music.stringPlayable("C D E F G A B C5 ", 650), music.PlaybackMode.UntilDone)
})
controller.player1.onButtonEvent(ControllerButton.Left, ControllerButtonEvent.Repeated, function () {
    bubble.tilt_angle(bubble.Choice.Left)
})
bubble.createBoard()
bubble.load_bubble()
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.One), sprites.create(img`
    ..........................dddd
    ..........6...............dd..
    ...........66..6666......ddd..
    ..........66666666667....dd...
    ......d...676666667667..ddd...
    .dddddd...667666666766..dd....
    .dddddd....667777766676ddd....
    ......dd...667dd7777767dd.....
    .......dd..66cd961dd977dd.....
    ........dd.666d86fdd6fbc......
    .........dd.6d6dddddbdd.......
    ..........dd6bddedddddb.......
    ...........ddcdddeebdda.......
    ............bcbddddddac.......
    ............caaaabbbaa........
    .............a5aaabaa5........
    ..............aaaaaaaa........
    ..............aa7aa55.........
    ...............a55555.........
    ...............a55575.........
    ...............a55555.........
    ...............aa5555.........
    ................aaaaa.........
    ...............a55555.........
    ..............aaaaaaa.........
    ..............a555555.........
    .............a5555555.........
    ............aaaaa5555.........
    ...........aa55555555.........
    ..........aa555a555555........
    ..........a55aaa555555........
    .........a555aa5555a755.......
    ........aa55aa57555a555.......
    .......aa55aa555555a555.......
    .......a55aa555a555a555a......
    ........aaaaaaaaaaaaaaaa......
    ..........bbbb...bbb..........
    ..........ddd....ddd..........
    .........ddd.....ddd..........
    ........ddd......ddd..........
    .......dddd......ddd..........
    ......dddd.......ddd..........
    ......ddd.........dd..........
    .....ddd..........dd..........
    .....dd...........dd..........
    ....ddd............dd.........
    ....dd.............ddd........
    ....dddd.............dd.......
    ..............................
    ..............................
    `, SpriteKind.Player))
mp.getPlayerSprite(mp.playerSelector(mp.PlayerNumber.One)).top = 102
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.Two), sprites.create(img`
    ............b.b..........
    .....bb....bb.bbbbb......
    ....bbbb.bbbcccccc.....b8
    cb8cc.cbbbccc8111c.....cc
    cb8bccb.bc8118111c...cbbc
    c888cbb.c81111cc1c..ccb8.
    8cbbc...c811c1111c..ccbc.
    ..c11...c8111ccccc.c1dc..
    ..cb1b..cc8ccb8888c111b..
    ..cc11...cbb88bbbbc11b...
    ...cd1c..cb8888ccc11c....
    ...cc11c.cb88888c11cc....
    ....cc11cc8c1188c1cc.....
    .....cc11c81111c1c.......
    ......cc1c888cccc........
    .......cceb8cecc.........
    ........ceeeec...........
    ........ce222c...........
    ........c1111c...........
    .......ccd11dcc..........
    .......ccd11dcc..........
    .......ccdd1dcc..........
    .......ccd1ddcc..........
    ........cccccc...........
    ........cbbcbb...........
    ........ccbccc...........
    .......cccbbcbc..........
    ......ccbbbcccb..........
    ......ceeecceee..........
    ......eeee.eeee..........
    `, SpriteKind.Player))
mp.getPlayerSprite(mp.playerSelector(mp.PlayerNumber.Two)).left = 100
mp.getPlayerSprite(mp.playerSelector(mp.PlayerNumber.Two)).top = 102
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.Three), sprites.create(img`
    ........eeeeeeeeeeeeeeee.......
    .......e222222222222eeeee......
    .......eeeddddffeeffffeee....e.
    eee...eeeee111ffee1ff1eee...e2e
    eee2..eeeee22222222222222ecee2e
    e222e.eee22cdc111111111c22ce22e
    eee21.eee2ccdcdd11111dddc2ee22.
    eee11.eee2cd111111111111c2ed2c.
    .dddddd1eee22222222222221cc1c..
    .d1111111dcd111eeeec111c11c1...
    ..d1111ccddccccdeedcccc11111...
    ...dd1ccdd11111eeee1111111c....
    .....11ccbbbbbbeeeebbbbbbbc....
    ......cccbbbbbbceccbbbbbbb.....
    .....ccccccccccbcccccccccc.....
    .....ccccbbbbbbccccbbbbbbb.....
    .....cccccccccccfcccccccccc....
    ...............................
    `, SpriteKind.Player))
mp.getPlayerSprite(mp.playerSelector(mp.PlayerNumber.Three)).top = 102
mp.getPlayerSprite(mp.playerSelector(mp.PlayerNumber.Three)).setPosition(45, 114)
